### PR TITLE
simple footer + sample layout grid

### PR DESCRIPTION
**Pull request by kemalfidan**
This PR gets started on the footer and grid layout of the events. Everything is bare bones and is meant to setup themes, colors, etc with material ui. I changed the linter's tab width to 4 spaces so a lot of files are changed. The most important parts are under components (footer and events grid) and in pages/index.  

Also I picked some random colors for the page so don't mind those.

Screen Shot 2021-02-02 at 3 33 52 PM

### CODE REVIEW

**Comment by tbatk** [comment]
LGTM!

**Comment by rluberto** [comment]
LGTM

**Review by rossketron — APPROVED** [review]
Looks good to me!

**Review by zaviermiller — APPROVED** [review]
very nice, glad we are using material :D

**Pull request merged**
